version: "2"

services:
  mpi_head:
    build: .
    # image: openmpi
    ports: 
      - "22"
    links: 
      - mpi_node
    networks:
      - net

    security_opt: 
      - seccomp:unconfined

    command:
      /usr/sbin/sshd -D

  mpi_node:
    build: .
    # image: openmpi
    networks:
      - net
  
    security_opt: 
      - seccomp:unconfined
    command:
      /usr/sbin/sshd -D

networks:
  net:
    driver: bridge